Avoid data overriding in multithreaded environment
songoda/EpicLevels pull request #4
Opened 2022-04-25 02:07 UTC by Rubenicos

Sometimes I see this error when someone login and their data is deleted, so I fixed it.
> [EpicLevels] An error occurred executing a MySQL query: Duplicate entry 'b1532110-c636-32f8-ac4c-baab98bf3514' for key 'PRIMARY'
> com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'b1532110-c636-32f8-ac4c-baab98bf3514' for key 'PRIMARY'

I also fixed a problem when a player has a lot of experience.

### Changes
*  Added `DataManager#getPlayerOrCreate(UUID, Consumer)` method.
*  When player data does not exist on registeredPlayers, the data will be obtained with getPlayerOrCreate (Completely async).
*  Now experience calculator return a double value.

2022-08-05 17:17 UTC, SpraxDev requested changes
Hi, I've tried reviewing your PR to my best ability:

1. Could you please direct your PR do the `development` branch? If there are conflicts or something ignore this request and I'll deal with them this time - We don't mention this anywhere right now 
2. I'm not really sure about the new `messenger` table - What's the use-case it's good for?

And I must say I'm certainty not happy about Exceptions just being printed to the console :/
It's better than just hiding them but in the future we really should improve this.

2022-08-05 17:17 UTC, SpraxDev commented on src/main/java/com/songoda/epiclevels/EpicLevels.java
> +        this.dataManager.close();
Shouldn't the DataManager be closed after the bulkUpdates have been finished? (not sure if they are async too)

2022-08-05 17:17 UTC, SpraxDev commented on src/main/java/com/songoda/epiclevels/database/DataManager.java
> +                if (result.next()) {
Shouldn't the callback be invoked with `null` if we don't find a player?

2022-08-05 17:17 UTC, SpraxDev commented on src/main/java/com/songoda/epiclevels/database/DataUpdaterAbstract.java
> +        if (!isEnabled()) {
Same thing about locking as a bit further up

2022-08-05 17:17 UTC, SpraxDev commented on src/main/java/com/songoda/epiclevels/database/DataUpdaterAbstract.java
> +            lock.readLock().unlock();
Same thing about locking as a bit further up

2022-08-05 17:17 UTC, SpraxDev commented on src/main/java/com/songoda/epiclevels/database/DataUpdaterAbstract.java
> +        lock.readLock().lock();
`#isEnabled()` just returns a boolean, could we avoid the lock and return instantly if it returns `false`?
(As `#setEnabled(boolean)` does not lock itself I don't see any benefit.

2022-08-05 17:17 UTC, SpraxDev commented on src/main/java/com/songoda/epiclevels/database/DataUpdater.java
> +        } else {
If we return inside the if we can get rid of the `else`-Block for better readability

2022-08-05 17:54 UTC, Rubenicos commented
> Hi, I've tried reviewing your PR to my best ability:
> 
> 1. Could you please direct your PR do the `development` branch? If there are conflicts or something ignore this request and I'll deal with them this time - We don't mention this anywhere right now

Done

> 2. I'm not really sure about the new `messenger` table - What's the use-case it's good for?

It's a new table only for communication purposes, all the hosts connected to the same database will receive update messages via `messenger` table to update cached player data (or boosts) in runtime without having the player online, then the rows are deleted.
In other words, for multi-host compatibility.

> And I must say I'm certainty not happy about Exceptions just being printed to the console :/ It's better than just hiding them but in the future we really should improve this.

Sure, actually I put that because it's almost impossible to get an error in those operations, but if you want i will remove it

2022-08-05 21:23 UTC, SpraxDev commented
> Sure, actually I put that because it's almost impossible to get an error in those operations, but if you want i will remove it

No I think you misunderstood - Please keep them in.
I think `#printStacktrace()` is better than not having it. What I don't like about it is that 90 % of our users do not or are unable to read the error logs. So we will never see them. Depending on when the error happens and what the consequences are, some of our plugins just get more broken over time because it is in an unexpected state.

I personally prefer for methods of this kind to throw the Exceptions and handle it somewhere higher in the *'list'* but I didn't fully read your code so maybe you already are at that high point I mean.

2022-08-14 12:01 UTC, SpraxDev approved these changes
Looks good to me - Thanks for your contribution!

2022-08-14 18:25 UTC, merged